### ISSUE TITLE
Incorrect behavior with slash in address object

### ISSUE THREAD

**Issue by fwiethof** [fortinet/terraform-provider-fortios#1]
When trying to add an address object with a "/" in the name, apply fails:

```
Error: Error applying plan:

1 error(s) occurred:

* fortios_firewall_object_address.test: 1 error(s) occurred:

* fortios_firewall_object_address.test: Error reading Firewall Object Address: status is error and error no is not found and http_status no is 400
```
Here's the main.tf:

```
resource "fortios_firewall_object_address" "test" {
  name = "test 10.0.0.0/24"
  type = "ipmask"
  subnet = "10.0.0.0/24"
}
```

After applying, the state seems to be broken. The object cannot be removed anymore.

The object is however, created on the firewall.
We assume there is an encoding issue with the URL.

**Comment by fwiethof** [comment]
I saw you're also working on the issues in https://github.com/terraform-providers/terraform-provider-fortios. Would you like me to open further issues rather there or here?

**Comment by fgtdev-hblu** [comment]
Hi fwiethof,

For further issues, please open under https://github.com/terraform-providers/terraform-provider-fortios. Thank you!

**Comment by fwiethof** [comment]
Continued here: https://github.com/terraform-providers/terraform-provider-fortios/issues/1
