### ISSUE TITLE
Add option to provider configuration to check firewall certificate

### ISSUE THREAD

**Issue by fwiethof** [fortinet/terraform-provider-fortios#2]
The provider accepts certificates from the firewall that it cannot verify.
This is a security issue, which is inacceptable for a security device like a firewall.
There should be an option to accept or reject invalid certificates.

**Comment by fwiethof** [comment]
Currently, the provider also accepts self signed or invalid certificates (expired, wrong CN) from the FortiGate.

This is a security risk, because we cannot detect man in the middle attacks between the Terraform workstation and the firewall that needs to be configured.

If there would be an option to enable certificate checking (accept insecure certificates true/false), then we can be almost sure we're talking to the correct firewall.

Talking to the wrong firewalls could reveal sensitive configuration information, such as but not limited to VPN PSKs.

Please let me know in case you need more information.

**Comment by fgtdev-hblu** [comment]
Hi fwiethof,

Thank you for the additional information. We are analyzing it. 

BTW, since the Terraform code has been released from terraform-providers repository, can we close the issue here and track them under https://github.com/terraform-providers/terraform-provider-fortios/issues instead?

**Comment by fwiethof** [comment]
Continued here: https://github.com/terraform-providers/terraform-provider-fortios/issues/2
