### ISSUE TITLE
Add import for resources

### ISSUE THREAD

**Issue by fwiethof** [fortinet/terraform-provider-fortios#3]
While waiting for the provider, we have already configured our FortiGate firewalls with outputs and copy&paste templates.

We now want to move to the new provider, but it looks like the import schema is missing, so a `terraform import` is not possible.

We do not want to reconfigure the whole firewall.

Please add an import option.

**Comment by fwiethof** [comment]
Please let me know in case you need more information.

**Comment by fgtdev-hblu** [comment]
Hi fwiethof,

Sure. We are analyzing it.

**Comment by fgtdev-hblu** [comment]
Hi fwiethof,

BTW, since the Terraform code has been released from terraform-providers repository, can we close the issue here and track them under https://github.com/terraform-providers/terraform-provider-fortios/issues instead? Thanks!

**Comment by fwiethof** [comment]
Continued here: https://github.com/fortinet/terraform-provider-fortios/issues/3
